package originresolver

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"
)

func EmitExample(spec Spec, scenarioID string) ([]byte, error) {
	scenario, ok := spec.scenarioMap()[scenarioID]
	if !ok {
		return nil, fmt.Errorf("scenario %q is not declared", scenarioID)
	}
	if scenario.Example == nil {
		return nil, fmt.Errorf("scenario %q has no Go example", scenarioID)
	}
	report, err := ResolveScenario(spec, scenarioID)
	if err != nil {
		return nil, err
	}
	if report.Status != StatusClosed {
		return nil, fmt.Errorf("scenario %q is %s and cannot emit a capture-free example", scenarioID, report.Status)
	}
	if err := validateIdentifier(scenario.Example.Package); err != nil {
		return nil, fmt.Errorf("example package: %w", err)
	}
	if err := validateIdentifier(scenario.Example.Function); err != nil {
		return nil, fmt.Errorf("example function: %w", err)
	}
	symbolEvidence := map[string]SymbolEvidence{}
	for _, evidence := range report.Symbols {
		symbolEvidence[evidence.ID] = evidence
	}
	referenceEvidence := map[string]ReferenceEvidence{}
	for _, evidence := range report.References {
		referenceEvidence[evidence.ID] = evidence
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by gooo-origin from .gooo metacode; DO NOT EDIT.\n")
	fmt.Fprintf(&source, "package %s\n\n", scenario.Example.Package)
	source.WriteString("import (\n\t\"crypto/sha256\"\n\t\"encoding/hex\"\n\t\"fmt\"\n\t\"strings\"\n)\n\n")
	source.WriteString("type generatedSymbol struct {\n\tID string\n\tSpelling string\n\tDeclarationOrigin string\n\tExpansionOrigin string\n\tCapturePolicy string\n}\n\n")
	fmt.Fprintf(&source, "const identityDelimiter = %s\n", strconv.Quote(spec.Semantics.Identity.Delimiter))
	fmt.Fprintf(&source, "const identityPrefix = %s\n", strconv.Quote(spec.Semantics.Identity.Prefix))
	fmt.Fprintf(&source, "const alphaSeparator = %s\n", strconv.Quote(spec.Semantics.AlphaRenaming.Separator))
	fmt.Fprintf(&source, "const alphaIdentityChars = %d\n\n", spec.Semantics.AlphaRenaming.IdentityChars)
	source.WriteString("func stableIdentity(symbol generatedSymbol) string {\n")
	source.WriteString("\tpayload := strings.Join([]string{symbol.DeclarationOrigin, symbol.ExpansionOrigin, symbol.ID}, identityDelimiter)\n")
	source.WriteString("\tsum := sha256.Sum256([]byte(payload))\n")
	source.WriteString("\treturn identityPrefix + hex.EncodeToString(sum[:])\n}\n\n")
	source.WriteString("func alphaName(symbol generatedSymbol, identity string, used map[string]bool) string {\n")
	source.WriteString("\tchars := alphaIdentityChars\n")
	source.WriteString("\tif chars > len(identity) { chars = len(identity) }\n")
	source.WriteString("\tcandidate := symbol.Spelling + alphaSeparator + identity[:chars]\n")
	source.WriteString("\tif !used[candidate] { return candidate }\n")
	source.WriteString("\tfor suffix := 1; ; suffix++ {\n")
	source.WriteString("\t\talternative := fmt.Sprintf(\"%s_%d\", candidate, suffix)\n")
	source.WriteString("\t\tif !used[alternative] { return alternative }\n\t}\n}\n\n")
	source.WriteString("func resolveNames() map[string]string {\n")
	source.WriteString("\tsymbols := []generatedSymbol{\n")
	for _, symbolID := range append(append([]string{}, scenario.DeclaredSymbols...), scenario.IntroducedSymbols...) {
		symbol := spec.declarationMap()[symbolID]
		fmt.Fprintf(&source, "\t\t{ID: %s, Spelling: %s, DeclarationOrigin: %s, ExpansionOrigin: %s, CapturePolicy: %s},\n", strconv.Quote(symbol.ID), strconv.Quote(symbol.Spelling), strconv.Quote(symbol.DeclarationOrigin), strconv.Quote(symbol.ExpansionOrigin), strconv.Quote(symbol.CapturePolicy))
	}
	source.WriteString("\t}\n\tnames := map[string]string{}\n\tused := map[string]bool{}\n\tfor _, symbol := range symbols {\n")
	source.WriteString("\t\tidentity := stableIdentity(symbol)\n\t\tname := symbol.Spelling\n")
	fmt.Fprintf(&source, "\t\tif symbol.CapturePolicy == %s && used[name] { name = alphaName(symbol, identity, used) }\n", strconv.Quote(spec.Semantics.AlphaRenaming.FreshPolicy))
	source.WriteString("\t\tnames[symbol.ID] = name\n\t\tused[name] = true\n\t}\n\treturn names\n}\n\n")
	fmt.Fprintf(&source, "func %s() string {\n", scenario.Example.Function)
	usedNames := map[string]bool{}
	for _, binding := range scenario.Example.Bindings {
		evidence, ok := symbolEvidence[binding.Symbol]
		if !ok {
			return nil, fmt.Errorf("example binding refers to missing symbol %q", binding.Symbol)
		}
		if err := validateIdentifier(evidence.EffectiveSpelling); err != nil {
			return nil, fmt.Errorf("effective spelling for %q: %w", binding.Symbol, err)
		}
		if usedNames[evidence.EffectiveSpelling] {
			return nil, fmt.Errorf("example binding reuses effective spelling %q", evidence.EffectiveSpelling)
		}
		usedNames[evidence.EffectiveSpelling] = true
		fmt.Fprintf(&source, "\t%s := %s\n", evidence.EffectiveSpelling, strconv.Quote(binding.Value))
	}
	returnEvidence, ok := referenceEvidence[scenario.Example.ReturnReference]
	if !ok {
		return nil, fmt.Errorf("example return refers to missing reference %q", scenario.Example.ReturnReference)
	}
	if err := validateIdentifier(returnEvidence.EffectiveSpelling); err != nil {
		return nil, fmt.Errorf("effective return spelling: %w", err)
	}
	fmt.Fprintf(&source, "\treturn %s\n}\n\n", returnEvidence.EffectiveSpelling)
	source.WriteString("func main() {\n\tresolved := resolveNames()\n")
	fmt.Fprintf(&source, "\tfmt.Println(%s(), resolved[%s])\n", scenario.Example.Function, strconv.Quote(returnEvidence.ExpectedTarget))
	source.WriteString("}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	return formatted, nil
}

func WriteCallerFile(path, repoRoot string, data []byte) error {
	if path == "" {
		return errors.New("output path is required")
	}
	absolutePath, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	absoluteRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return err
	}
	relative, err := filepath.Rel(absoluteRoot, absolutePath)
	if err != nil {
		return err
	}
	if relative == "." || (relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator))) {
		return errors.New("caller-owned output must be outside the target repository")
	}
	if err := os.MkdirAll(filepath.Dir(absolutePath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(absolutePath, data, 0o644)
}

func validateIdentifier(value string) error {
	if value == "" {
		return errors.New("identifier is empty")
	}
	for index, character := range []rune(value) {
		if index == 0 {
			if !unicode.IsLetter(character) && character != '_' {
				return fmt.Errorf("%q is not a Go identifier", value)
			}
			continue
		}
		if !unicode.IsLetter(character) && !unicode.IsDigit(character) && character != '_' {
			return fmt.Errorf("%q is not a Go identifier", value)
		}
	}
	keywords := map[string]bool{"break": true, "default": true, "func": true, "interface": true, "select": true, "case": true, "defer": true, "go": true, "map": true, "struct": true, "chan": true, "else": true, "goto": true, "package": true, "switch": true, "const": true, "fallthrough": true, "if": true, "range": true, "type": true, "continue": true, "for": true, "import": true, "return": true, "var": true}
	if keywords[value] {
		return fmt.Errorf("%q is a Go keyword", value)
	}
	return nil
}
